import numpy as np

In [2]:
np.__version__

'1.24.3'

In [3]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [4]:
arr = np.arange(0,100)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.array([0,1,2,3,4])

array([0, 1, 2, 3, 4])

In [9]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
l=[1,2,3,4,5]

In [11]:
l

[1, 2, 3, 4, 5]

In [ ]:
#difference between list and array

In [13]:
l2=[ x for x in range(0,10)]

In [14]:
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
l3=[str(x) for x in l2]

In [16]:
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [18]:
l4=[x**2 for x in l2]

In [19]:
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [20]:
import array

In [22]:
arr=array.array('i',l2)

In [23]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
type(arr)

array.array

In [26]:
arr1=array.array('i',[x**2 for x in l2])

In [27]:
arr1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [28]:
import numpy

In [29]:
np.array(l2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.array([x+3 for x in range(0,10)])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
np.array([x-3 for x in range(0,10)])

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [34]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [35]:
np.array([1,2,3,6],dtype='float')

array([1., 2., 3., 6.])

In [36]:
np.array([1,2,3,6],dtype='str')

array(['1', '2', '3', '6'], dtype='<U1')

In [37]:
np.array([1,2,3,6],dtype=float)

array([1., 2., 3., 6.])

In [38]:
np.array([1,2,3,6],dtype=np.float32)

array([1., 2., 3., 6.], dtype=float32)

In [39]:
l2d=[[1,2,3],[4,5,6]]

In [40]:
l2d

[[1, 2, 3], [4, 5, 6]]

In [41]:
lc2d=[range(i,i+3) for i in [1,3]]

In [43]:
np.array(lc2d)

array([[1, 2, 3],
       [3, 4, 5]])

In [52]:
lc3d=[range(i,i+3) for i in [1,4,7]]

In [53]:
np.array(lc3d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
np.zeros([2,2],dtype=int)

array([[0, 0],
       [0, 0]])

In [60]:
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [61]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [63]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [64]:
arr=np.zeros((3,4))

In [65]:
arr[1:2,1:3]=1

In [66]:
arr

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [68]:
arr=np.zeros((10,10))

In [69]:
arr[1:9,1:9]=1

In [70]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [71]:
arr[2:8,2:8]=2

In [72]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [73]:
arr[3:7,3:7]=3

In [74]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 3., 3., 3., 3., 2., 1., 0.],
       [0., 1., 2., 3., 3., 3., 3., 2., 1., 0.],
       [0., 1., 2., 3., 3., 3., 3., 2., 1., 0.],
       [0., 1., 2., 3., 3., 3., 3., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
ar=np.arange(0,9,dtype='float').reshape(3,3)

In [78]:
ar[:]=3.14

In [79]:
ar

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [80]:
np.full((3,4),3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [81]:
np.full((3,4),'abc')

array([['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc']], dtype='<U3')

In [83]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [84]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
#pythonlist
#listcomprehension
#array module(import lib array)
#numpy array:
    #zeros
    #ones
    #full
    #eye
    #arange
    #reshape
    #indexing

In [3]:
import numpy as np

In [5]:
np.full([6,6],64)

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

In [6]:
#Linspace - Linearlly spaced elements
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
np.linspace(0,0.1,5)

array([0.   , 0.025, 0.05 , 0.075, 0.1  ])

In [8]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [9]:
np.linspace(15,20,20)

array([15.        , 15.26315789, 15.52631579, 15.78947368, 16.05263158,
       16.31578947, 16.57894737, 16.84210526, 17.10526316, 17.36842105,
       17.63157895, 17.89473684, 18.15789474, 18.42105263, 18.68421053,
       18.94736842, 19.21052632, 19.47368421, 19.73684211, 20.        ])

In [10]:
np.random.random((3,3))

array([[0.35019173, 0.0283736 , 0.57834758],
       [0.84492404, 0.10374998, 0.39376843],
       [0.5533278 , 0.68176836, 0.62855054]])

In [11]:
np.random.random(3)

array([0.58622221, 0.19949241, 0.18665762])

In [12]:
np.random.random((2,2))
#values b/w 0 and 1

array([[0.95539274, 0.3444238 ],
       [0.44261946, 0.56438004]])

In [18]:
np.random.normal(0,1,10)
#values with mean 0 and std dev 1

array([ 0.94928083,  0.10227294,  0.15900806, -0.14241369,  0.15285278,
        0.27746   ,  0.6187475 ,  1.56890115, -0.23251743, -0.10452618])

In [17]:
np.random.normal(0,1,(2,2))

array([[-0.30771105, -1.76286958],
       [ 0.97307286, -0.05651262]])

In [22]:
np.random.seed(10)
np.random.random(10)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [23]:
np.random.randint(50,100,36)

array([86, 66, 86, 97, 61, 74, 93, 83, 58, 86, 64, 99, 63, 55, 63, 75, 63,
       78, 72, 80, 80, 75, 62, 51, 81, 86, 77, 68, 79, 63, 72, 73, 80, 61,
       78, 60])

In [24]:
#operation on numpy array

In [28]:
arr=np.random.randint(0,100,(2,2))

In [29]:
arr

array([[71, 88],
       [88, 50]])

In [30]:
arr.ndim
#number of dimensions

2

In [31]:
arr.size
#number of elements in an array

4

In [32]:
arr.shape

(2, 2)

In [33]:
arr.dtype

dtype('int32')

In [35]:
arr1=np.random.randint(0,40,10)

In [36]:
arr1

array([34, 15, 13, 24, 15,  6, 21, 22, 11, 12])

In [37]:
arr1[0]

34

In [39]:
arr1[4]

15

In [40]:
arr1[-1]

12

In [42]:
arr1[:4]

array([34, 15, 13, 24])

In [43]:
arr1[4:]

array([15,  6, 21, 22, 11, 12])

In [44]:
arr1[4:7]

array([15,  6, 21])

In [45]:
arr1[3]=45

In [46]:
arr1

array([34, 15, 13, 45, 15,  6, 21, 22, 11, 12])

Numpy Assignment

In [4]:
import numpy as np

In [31]:
a1 = np.array([range(i,i+3) for i in [1,4,7]])

In [32]:
np.array(a1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a2 = np.array([range(i,i+3) for i in [1,3]])

In [34]:
np.array(a2)

array([[1, 2, 3],
       [3, 4, 5]])

In [35]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [39]:
a2.dtype

dtype('int32')

In [37]:
np.array([x+1 for x in range(0,5)])

array([1, 2, 3, 4, 5])

In [38]:
a1.dtype

dtype('int32')

In [40]:
a2.ndim

2

In [41]:
a1.ndim

2

In [42]:
a1.shape

(3, 3)

In [43]:
a2.shape

(2, 3)

In [44]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
Maths = np.random.randint(0,100,20)

In [48]:
Maths

array([44, 37, 10, 34, 40, 13, 94, 52, 34, 40, 80, 20, 54, 66, 95, 29, 19,
       17, 52, 67])

In [50]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [1]:
import numpy as np

In [3]:
arr2 = np.random.randint(0,40,10)

In [4]:
arr2

array([ 8, 28,  4, 28, 32, 33, 13, 27, 33, 22])

In [6]:
arr2[2:6:2]

array([ 4, 32])

In [8]:
arr2[:]

array([ 8, 28,  4, 28, 32, 33, 13, 27, 33, 22])

In [9]:
#reverse
arr2

array([ 8, 28,  4, 28, 32, 33, 13, 27, 33, 22])

In [11]:
arr2[::-1]

array([22, 33, 27, 13, 33, 32, 28,  4, 28,  8])

In [12]:
arr2[::-2]

array([22, 27, 33, 28, 28])

In [20]:
a=np.arange(0,25).reshape(5,5)

In [21]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
a[0:3,0:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [27]:
a[2:5,3:5]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [2]:
import numpy as np

In [3]:
a=np.arange(0,25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
a[0,1:4]

array([1, 2, 3])

In [5]:
a[0,1]

1

In [6]:
a[2,1]

11

In [7]:
a[3,3]

18

In [8]:
a[2,4]

14

In [9]:
a[0:3,1]

array([ 1,  6, 11])

In [10]:
a[0:2,1]

array([1, 6])

In [11]:
a[0:3,0:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [12]:
a[0:3,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [13]:
a[2:,3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [14]:
a[2:5,3:5]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [15]:
#even numbers
a[::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [16]:
a[::,::]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
a[::2,::]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [18]:
a[::,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [19]:
a[::-1,::]

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [20]:
a[::-1,::-1]

array([[24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [28]:
a1=np.ones((10,10))

In [29]:
a1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [30]:
a1[1:9,1:9]=0
a1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [31]:
#Shallow copy
b=a[3:5,3:5]

In [32]:
b

array([[18, 19],
       [23, 24]])

In [33]:
b[1,1]=200
b

array([[ 18,  19],
       [ 23, 200]])

In [34]:
a

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23, 200]])

In [35]:
a[2,4]

14

In [38]:
c=a[2,4]=300

In [39]:
a

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13, 300],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23, 200]])

In [40]:
#Deep Copy
a[:2,:2]

array([[0, 1],
       [5, 6]])

In [48]:
da=a[:2,:2].copy
da

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [55]:
da[1,1]=15
da

TypeError: 'builtin_function_or_method' object does not support item assignment

In [46]:
a[0,0]=11
a

array([[ 11,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13, 300],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23, 200]])

In [59]:
t = np.arange(3)

In [60]:
t

array([0, 1, 2])

In [61]:
t.reshape(3,1)

array([[0],
       [1],
       [2]])

In [68]:
p = np.arange(1,5)

In [69]:
p

array([1, 2, 3, 4])

In [85]:
p=p.reshape(2,2)
p

array([[1, 2],
       [3, 4]])

In [86]:
ar=np.array([1,2,3])
ar

array([1, 2, 3])

In [87]:
ar.reshape(3,1)

array([[1],
       [2],
       [3]])

In [88]:
ar.reshape(1,3)

array([[1, 2, 3]])

In [89]:
p.reshape(1,4)

array([[1, 2, 3, 4]])

In [90]:
p

array([[1, 2],
       [3, 4]])

In [91]:
p.ravel()

array([1, 2, 3, 4])

In [103]:
p=p.flatten()

In [104]:
p

array([1, 2, 3, 4])

In [106]:
p[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [116]:
#Concatenation , Joining of two arrays
a1=np.arange(0,9).reshape(3,3)
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [121]:
b1=np.arange(9,18).reshape(3,3)
b1

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [122]:
np.concatenate([a1,b1])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [123]:
np.concatenate([a1,b1],axis=1) #axis to specify row 0/column 1

array([[ 0,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

In [1]:
import numpy as np

In [7]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                [6,5,4]])

In [8]:
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [9]:
np.hstack((x,[4]))

array([1, 2, 3, 4])

In [16]:
ar = np.array([[1,3],
             [4,5]])
ar

array([[1, 3],
       [4, 5]])

In [19]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [20]:
x

array([1, 2, 3])

In [21]:
np.hstack([ar,grid])

array([[1, 3, 9, 8, 7],
       [4, 5, 6, 5, 4]])

In [25]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [26]:
np.split(a,5)

[array([1]), array([2]), array([3]), array([4]), array([5])]

In [27]:
np.split(a,[2,3])

[array([1, 2]), array([3]), array([4, 5])]

In [28]:
np.split(a,[1,4])

[array([1]), array([2, 3, 4]), array([5])]

In [29]:
np.split(a,[1,2,4])

[array([1]), array([2]), array([3, 4]), array([5])]

In [30]:
ar1 = np.arange(0,25).reshape(5,5)
ar1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
np.hsplit(ar1,[2,3])

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24]])]

In [32]:
np.vsplit(ar1,[2,3])

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])]

In [33]:
np.vsplit(ar1,5)

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]])]

In [34]:
np.hsplit(ar1,5)

[array([[ 0],
        [ 5],
        [10],
        [15],
        [20]]),
 array([[ 1],
        [ 6],
        [11],
        [16],
        [21]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24]])]

In [37]:
ar2 = np.arange(0,16).reshape(4,4)
ar2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
np.vsplit(ar2,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [40]:
np.hsplit(ar2,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [42]:
#sum mean stddev varience sin cos theta log in numpy
#hstack vstack split hsplit vsplit aggregation
np.abs(-4)

4

In [43]:
a

array([1, 2, 3, 4, 5])

In [44]:
np.sum(a)

15

In [45]:
ar

array([[1, 3],
       [4, 5]])

In [46]:
np.sum(ar)

13

In [47]:
np.sum(ar,axis=0)

array([5, 8])

In [48]:
np.sum(ar,axis=1)

array([4, 9])

In [49]:
np.min(a)

1

In [50]:
np.max(a)

5

In [51]:
np.min(ar)

1

In [52]:
np.max(ar)

5

In [53]:
np.min(ar,axis=0)

array([1, 3])

In [54]:
np.max(ar,axis=1)

array([3, 5])

In [55]:
np.argmin(a) #index of min element

0

In [56]:
np.argmin(ar)

0

In [57]:
np.argmax(ar)

3

In [58]:
np.argmax(a)

4

In [59]:
i=-3
np.absolute(i)

3

In [60]:
np.var(ar)

2.1875

In [61]:
np.var(a)

2.0

In [62]:
np.std(ar)

1.479019945774904

In [63]:
np.std(a)

1.4142135623730951

In [64]:
np.median(a)

3.0

In [65]:
np.prod(a) #factorial

120

In [2]:
np.log(2)

0.6931471805599453

In [5]:
np.floor(23/4)

5.0

In [7]:
np.ceil(23/4)

6.0

In [8]:
np.percentile?

In [10]:
np.empty?

In [14]:
a = np.arange(5)
b = np.full(5,5)
print(a,b)

[0 1 2 3 4] [5 5 5 5 5]


In [15]:
a + b

array([5, 6, 7, 8, 9])

In [18]:
c = np.full(2,3)[:,np.newaxis]
c

array([[3],
       [3]])

In [19]:
b+c

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [30]:
d = np.full(2,3)
e = np.full(2,1)[:,np.newaxis]
s = d + e
display(d,e)
display(d+e,s)
display(s+5)

array([3, 3])

array([[1],
       [1]])

array([[4, 4],
       [4, 4]])

array([[4, 4],
       [4, 4]])

array([[9, 9],
       [9, 9]])

In [34]:
a1 = np.ones((3,3))
b1 = np.arange(3)
display(a1,b1)
display(a1+b1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([0, 1, 2])

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [35]:
a

array([0, 1, 2, 3, 4])

In [36]:
a>1

array([False, False,  True,  True,  True])

In [37]:
a==2

array([False, False,  True, False, False])

In [38]:
a==0

array([ True, False, False, False, False])

In [39]:
a<1

array([ True, False, False, False, False])

# Assignment

Question 1

In [1]:
import numpy as np

Question 2

In [2]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Question 3

In [3]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Question 4

In [4]:
c = np.array([x+1 for x in range(9,50)])
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Question 5

In [5]:
d = np.arange(10,50,2)
d

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

Question 6

In [6]:
e = np.arange(0,9).reshape(3,3)
e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Question 7

In [7]:
f = np.eye(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Question 8

In [8]:
g = np.random.random(1)
g

array([0.3237306])

Question 9

In [9]:
h = np.random.normal(0,40,25)
h

array([ 17.2461225 , -25.50696065,  60.45948709, -49.38260217,
       -25.19051928,  16.3200873 ,   0.52174543,  45.33795676,
        23.85313925, -20.2296143 , -36.43533629,   0.21971487,
        -8.56265612, -72.45763502, -45.11987846,  20.74330709,
       -24.64669374,   1.73357983, -40.11523625,  15.48135003,
        -1.70546672,   8.56267012, -42.54221132,  84.88096692,
        18.05001747])

Question 10

In [10]:
i = np.linspace(0.01,1,100).reshape(10,10)
i

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

Question 11

In [11]:
j = np.linspace(0,1,20)
j

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Question 12

In [12]:
k = np.arange(1,26).reshape(5,5)
k

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
#a
k[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [14]:
#b
k[3,4]

20

In [15]:
#c
k[0:3,1]

array([ 2,  7, 12])

In [16]:
#d
k[4,0:5]

array([21, 22, 23, 24, 25])

In [17]:
#e
k[3:5,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Question 13

In [18]:
np.sum(k)

325

Question 14

In [19]:
np.sum(k,axis=0)

array([55, 60, 65, 70, 75])

Question 15

Question 15

In [20]:
np.std(k)

7.211102550927978

In [21]:
np.var(k)

52.0

In [22]:
np.min(k,axis=1)

array([ 1,  6, 11, 16, 21])

In [23]:
np.max(k,axis=1)

array([ 5, 10, 15, 20, 25])

Question 16

# Exercise 2

Question 1

In [13]:
a = np.array([0,1,2,3,4,5],dtype = 'float')
a

array([0., 1., 2., 3., 4., 5.])

In [6]:
b = np.arange(0,4).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [26]:
c = np.arange(0,18).reshape(2,3,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

Question 2

In [27]:
a.dtype

dtype('float64')

In [28]:
b.dtype

dtype('int32')

In [29]:
c.dtype

dtype('int32')

Question 3

In [30]:
a.shape

(6,)

In [31]:
b.shape

(2, 2)

In [32]:
c.shape

(2, 3, 3)

In [33]:
a.ndim

1

In [34]:
b.ndim

2

In [35]:
c.ndim

3

Question 4

In [37]:
d = np.zeros(12)
d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Question 5

In [62]:
d1 = np.ones(4).reshape(2,2)
d1

array([[1., 1.],
       [1., 1.]])

Question 6

In [63]:
e = np.random.randint(0,100,20)
e

array([71, 27, 93, 63, 41, 75, 91, 88, 39,  7, 21, 93, 65, 94, 67, 11, 59,
       37, 50, 91])

Question 7

In [64]:
e1 = np.sort(e)
e1

array([ 7, 11, 21, 27, 37, 39, 41, 50, 59, 63, 65, 67, 71, 75, 88, 91, 91,
       93, 93, 94])

In [65]:
e2 = np.sort(e)[::-1]
e2

array([94, 93, 93, 91, 91, 88, 75, 71, 67, 65, 63, 59, 50, 41, 39, 37, 27,
       21, 11,  7])

Question 8

In [66]:
e[3:7]

array([63, 41, 75, 91])

In [67]:
ec1 = np.copy(e1)

In [71]:
ec1[4]=8

In [72]:
ec1

array([ 7, 11, 21, 27,  8, 39, 41, 50, 59, 63, 65, 67, 71, 75, 88, 91, 91,
       93, 93, 94])

In [73]:
e1

array([ 7, 11, 21, 27, 37, 39, 41, 50, 59, 63, 65, 67, 71, 75, 88, 91, 91,
       93, 93, 94])

Question 9

In [75]:
f = np.eye(5,5)
f

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
f.flatten()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [80]:
f.ravel()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

Questin 10

In [93]:
g = np.arange(0,25).reshape(5,5)
g

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [95]:
h = np.array([25,26,27,28,29]).reshape(1,5)
h

array([[25, 26, 27, 28, 29]])

In [96]:
i = np.concatenate([g,h])
i

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

Question 11

In [98]:
np.vsplit(i,[2,5])

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29]])]

In [100]:
np.hsplit(i,[2,4])

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23],
        [27, 28]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29]])]

Question 12

In [101]:
a1 = np.eye(4)
a1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [102]:
b1 = a1+4
b1

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

Question 13

In [131]:
c1 = np.array([0.4761,1.3452,1.9873,3.6574,4.2845,5.2056])
c1

array([0.4761, 1.3452, 1.9873, 3.6574, 4.2845, 5.2056])

In [143]:
np.ceil(c1*100)/100

array([0.48, 1.35, 1.99, 3.66, 4.29, 5.21])

In [144]:
np.floor(c1*100)/100

array([0.47, 1.34, 1.98, 3.65, 4.28, 5.2 ])

In [145]:
np.round(c1,2)

array([0.48, 1.35, 1.99, 3.66, 4.28, 5.21])

Question 14

In [147]:
d1 = np.arange(0,25).reshape(5,5)
d1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [149]:
np.min(d1,axis=0)

array([0, 1, 2, 3, 4])

In [151]:
np.max(d1,axis=0)

array([20, 21, 22, 23, 24])

In [155]:
np.var(d1,axis=0)

array([50., 50., 50., 50., 50.])

In [156]:
np.std(d1,axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

Question 15

In [166]:
nv = np.empty(8)
nv.fill(0)
nv

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [167]:
nv[6]=200
nv

array([  0.,   0.,   0.,   0.,   0.,   0., 200.,   0.])

Question 16

In [178]:
ar = np.arange(100,151)
ar

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

Question 17

In [179]:
np.sort(ar)[::-1]

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

Question 18

In [180]:
m = np.arange(0,25).reshape(5,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Question 19

In [181]:
n = np.array([1,0,2,0,0,4,0,8])
n

array([1, 0, 2, 0, 0, 4, 0, 8])

In [182]:
np.nonzero?

In [183]:
np.nonzero(n)[0]

array([0, 2, 5, 7], dtype=int64)

Question 20

In [187]:
o = np.ones((10,10))
o

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [189]:
o[1:9,1:9]=0
o

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Question 21

In [197]:
p = np.ones((8,8))
p

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [198]:
p[::2,::2]=0
p

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [199]:
p[1::2,1::2]=0
p

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

Question 22

In [203]:
q = np.random.randint(0,25,9).reshape(3,3)
q

array([[ 8,  0, 21],
       [ 6, 20, 16],
       [21, 19,  6]])

In [204]:
r = np.random.randint(0,25,9).reshape(3,3)
r

array([[23,  8,  0],
       [17, 22, 18],
       [ 2,  7, 17]])

In [205]:
q+r

array([[31,  8, 21],
       [23, 42, 34],
       [23, 26, 23]])

In [206]:
q*r

array([[184,   0,   0],
       [102, 440, 288],
       [ 42, 133, 102]])

In [207]:
q-r

array([[-15,  -8,  21],
       [-11,  -2,  -2],
       [ 19,  12, -11]])